server:
  port: 8761

spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:https://configserverorquideas.onrender.com

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${HOSTNAME}:${server.port}
    metadata-map:
      zone: primary
  client:
    register-with-eureka: true
    fetch-registry: true