spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://microservice-oauth-84gq.onrender.com

  cloud:
    gateway:
      server:
        webflux:
          # CORS global
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - https://orquideas-frontend-kou4.vercel.app/
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowed-headers:
                  - "*"
                allow-credentials: true

          # Rutas del gateway
          routes:
            - id: microservice-users
              uri: https://microservice-users-hzyz.onrender.com
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=2

            - id: microservice-bus
              uri: https://microservice-bus.onrender.com
              predicates:
                - Path=/api/bus/**
              filters:
                - StripPrefix=2

            - id: microservice-travel
              uri: https://microservice-travel.onrender.com
              predicates:
                - Path=/api/rutas/**
              filters:
                - StripPrefix=1

            - id: microservice-travel
              uri: https://microservice-travel.onrender.com
              predicates:
                - Path=/api/viajes/**
              filters:
                - StripPrefix=2

            - id: microservice-payment
              uri: https://microservice-pagos.onrender.com
              predicates:
                - Path=/api/pagos/**
              filters:
                - StripPrefix=2

            - id: microservice-parcels
              uri: https://microservice-encomiendas.onrender.com
              predicates:
                - Path=/api/encomiendas/**
              filters:
                - StripPrefix=2

            - id: microservice-oauth
              uri: https://microservice-oauth-84gq.onrender.com
              predicates:
                - Path=/api/seguridad/**
              filters:
                - StripPrefix=2